source 'https://rubygems.org'

gem 'jekyll'
gem 'jemoji'
gem 'html-proofer'
gem 'jekyll-paginate'
gem 'jekyll-github-metadata'
gem 'jekyll-mentions'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jemoji'
